site_name: itembed
site_url: http://jojolebarjos.github.io/itembed
repo_url: https://github.com/jojolebarjos/itembed

nav:
  - Home: index.md
  - Math: math.md
  - API: api.md

theme:
  name: material
  features:
    - content.code.copy

plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            show_root_heading: true
            show_source: false
            docstring_style: numpy
  - bibtex:
      bib_file: docs/references.bib

markdown_extensions:
  - admonition
  - footnotes
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

watch:
  - src
