site_name: itembed
site_url: http://jojolebarjos.github.io/itembed
repo_url: https://github.com/jojolebarjos/itembed

nav:
  - Home: index.md
  - Getting started: start.md
  - Mathematical details: math.md
  - User interface: api.md

theme:
  name: material
  features:
    - content.code.copy
    - navigation.footer
    - navigation.indexes
    - navigation.sections
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.suggest
    - toc.follow
  palette:
    primary: black
    accent: indigo

plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            docstring_style: numpy
            show_root_heading: true
            show_root_full_path: false
            line_length: 88
            show_source: true
            show_signature: true
            show_signature_annotations: true
            separate_signature: true
            signature_crossrefs: true
  - bibtex:
      bib_file: docs/references.bib

markdown_extensions:
  - admonition
  - footnotes
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - toc:
      permalink: "#"

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra_css:
  - stylesheets/extra.css

watch:
  - src
