name: Publish to PyPI

on:
  push:
    tags:
    - "*.*.*"

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build

    - name: Build binary wheel and source tarball
      run: |
        python -m build

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: python-package-distributions
        path: ./dist/

  publish:
    needs: build

    runs-on: ubuntu-latest

    environment:
      name: testpypi
      url: https://test.pypi.org/p/itembed

    permissions:
      id-token: write

    steps:

    - name: Download artifact
      uses: actions/download-artifact@v3
      with:
        name: python-package-distributions
        path: ./dist/

    - name: Publish to TestPyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        repository-url: https://test.pypi.org/legacy/

  release:
    needs: publish

    runs-on: ubuntu-latest

    permissions:
      contents: write
      id-token: write

    steps:

    - name: Download artifact
      uses: actions/download-artifact@v3
      with:
        name: python-package-distributions
        path: ./dist/

    - name: Sign with Sigstore
      uses: sigstore/gh-action-sigstore-python@v1.2.3
      with:
        inputs: >-
          ./dist/*.tar.gz
          ./dist/*.whl

    - name: Create GitHub Release
      env:
        GITHUB_TOKEN: ${{ github.token }}
      run: >-
        gh release create
        '${{ github.ref_name }}'
        --repo '${{ github.repository }}'
        --notes ""

    - name: Upload artifact signatures to GitHub Release
      env:
        GITHUB_TOKEN: ${{ github.token }}
      run: >-
        gh release upload
        '${{ github.ref_name }}' dist/**
        --repo '${{ github.repository }}'
